apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyrbot
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: tyrbot
        image: fatpower/tyrbot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 100m
            memory: 250Mi
        volumeMounts:
        - name: tyrbot-conf-volume
          mountPath: /app/conf
          readOnly: true
      volumes:
      - name: tyrbot-conf-volume
        secret:
          secretName: tyrbot-conf
